### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by marlonmarques** [leandrocfe/filament-ptbr-form-fields#2]
### What happened?

Erro na instalação

### How to reproduce the bug

Quando tento instalar recebo esse erro:
 
 Problem 1
    - Root composer.json requires leandrocfe/filament-ptbr-form-fields * -> satisfiable by leandrocfe/filament-ptbr-form-fields[dev-master, dev-develop, 0.1.0, 9999999-dev].
    - leandrocfe/filament-ptbr-form-fields[dev-master, dev-develop, 0.1.0] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require leandrocfe/filament-ptbr-form-fields:*" to figure out if any version is installable, or "composer require leandrocfe/filament-ptbr-form-fields:^2.1" if you know which you need.

### Package Version

2.17.36

### PHP Version

8.1.17

### Laravel Version

9.19

**Comment by leandrocfe** [comment]
composer update?

**Comment by leandrocfe** [comment]
É necessário o laravel 10
