### ISSUE TITLE
Atualização para o filament v3

### ISSUE THREAD

**Issue by davigs** [leandrocfe/filament-ptbr-form-fields#7]
### What happened?

Tem alguma previsão para atualização do pacote para o filament v3?

### How to reproduce the bug

https://filamentphp.com/docs/3.x/panels/upgrade-guide

### Package Version

0.1.0

### PHP Version

8.2.0

### Laravel Version

10.17.0

### Which operating systems does with happen with?

macOS

**Comment by davigs** [comment]
Maravilha @leandrocfe muito obrigado pelo retorno.

**Comment by davigs** [comment]
Opa @leandrocfe tudo certo? Cara desculpa a insistência mas é que meu projeto depende da sua lib para rodar e sem ela não consigo atualizar o filament, tem alguma coisa que eu possa fazer para ajudar? Tenho interesse na atualização da lib pois é importante para meu projeto.

**Comment by leandrocfe** [comment]
opa, beleza? Eu estou programando mexer nisso ainda essa semana.

**Comment by leandrocfe** [comment]
@davigs , pode testar essa versão por favor?
https://github.com/leandrocfe/filament-ptbr-form-fields/tree/3.0.0

**Comment by davigs** [comment]
Opa @leandrocfe tudo certo? Funcionou perfeitamente, já atualizei o projeto e consegui rodar o filament v3. Muito obrigado pela atenção.
