### ISSUE TITLE
[Bug]:  Componente Money não está atualizandocorretamente os valores no Banco - Filament V3.

### ISSUE THREAD

**Issue by mclgms** [leandrocfe/filament-ptbr-form-fields#9]
### What happened?

O componente Money ao salvar o registro durante a criação está salvando o dado corretamente.
Na edição, ele acrescenta "0" no valor original.

***Exemplo: 
- Na criação do registro: R$ 200,00. 
- Ao editar, o registro é salvo como R$ 2.000,00.

### How to reproduce the bug

- Crie um registro qualquer com o valor R$ 200,00
- Edite o valor sem alterar nada, apenas salve o registro, o valor do campo será gravado com R$ 2.000,00.

### Package Version

3.0.0

### PHP Version

8.2

### Laravel Version

10.20.0

### Which operating systems does with happen with?

Linux

### Notes

No banco o campo foi definido como: decimal(10,2)

**Comment by mliell** [comment]
O bug também acontece uilizando MoneyCast (https://filamentphp.com/docs/3.x/panels/getting-started#casting-the-price-to-an-integer) e salvando  como integer no banco. Segue vídeo com teste:

[Gravação de tela de 2023-08-24 14-27-46.webm](https://github.com/leandrocfe/filament-ptbr-form-fields/assets/4391791/6ff8867e-51f6-435b-a483-3c004fd16ecb)

**Comment by mtbossa** [comment]
Eu queria saber como adicionar uma eule de valor mínimo. Tentei utilizar o 'min:1' do Laravel, ou o min() do Filament, mas nenhum funciona (nada acontece). A única forma que eu encontrei foi fazer um minLength() com o valor mínimo de caracteres. 

Tentei adicionar uma custom rule com Closure, mas a variável $value as vezes vem estranha, exemplo: R$ 200,00 no input, a variável $rule está como '0,200' na Closure.

**Comment by mclgms** [comment]
Leandro, bom dia.

Sim, resolveu.
Muito obrigado!

Atenciosamente

Marcelo Gomes |  MG Consultoria e Serviços de TI
Fixo : (11) 2214-3585  /  Móvel: (11) 9 8364-3775




------ Mensagem original ------
De "Leandro Costa Ferreira" ***@***.***>
Para "leandrocfe/filament-ptbr-form-fields" 
***@***.***>
Cc "Marcelo Gomes" ***@***.***>; "Mention" 
***@***.***>
Data 30/08/2023 15:08:22
Assunto Re: [leandrocfe/filament-ptbr-form-fields] [Bug]: Componente 
Money não está atualizandocorretamente os valores no Banco - Filament 
V3. (Issue #9)

**Comment by leandrocfe** [comment]
> Eu queria saber como adicionar uma rule de valor mínimo. Tentei utilizar o 'min:1' do Laravel, ou o min() do Filament, mas nenhum funciona (nada acontece). A única forma que eu encontrei foi fazer um minLength() com o valor mínimo de caracteres.
> 
> Tentei adicionar uma custom rule com Closure, mas a variável valueasvezesvemestranha,exemplo:R 200,00 no input, a variável $rule está como '0,200' na Closure.

@mtbossa 
Por favor, abra uma nova issue pra gente verificar. Obrigado!

**Comment by AdrianoMauricio1994** [comment]
Estou com o bug idêntico ao @mclgms, no momento de editar o registro é acrescido um 0 no final do valor original

**Comment by AdrianoMauricio1994** [comment]
Estou com o mesmo problema do @mclgms , é sempre adicionado um 0 a cada edit feito no registro

**Comment by guilhermemelgarejo** [comment]
Estou tendo o mesmo problema agora, versão atualizada.

**Comment by hjJunior** [comment]
Eu fiz algumas atualizacoes locais e me parece estar tudo ok, para quem quiser criar manualmente o field:

```php
<?php

namespace App\Forms\Components;

use Filament\Forms\Components\TextInput;
use Illuminate\Support\Str;

class Money extends TextInput
{
    protected string|int|float|null $initialValue = '0,00';

    protected function setUp(): void
    {
        $this
            ->prefix('R$')
            ->maxLength(13)
            ->extraAlpineAttributes([
                'x-mask:dynamic' => '$money($input, ",", ".", 2)'
            ])
            ->prefix('R$')
            ->maxLength(13)
            ->dehydrateMask()
            ->default(0.00)
            ->formatStateUsing(fn($state) => $state ? number_format(floatval($state), 2, ',', '.') : $this->initialValue);
    }

    public function dehydrateMask(bool|\Closure $condition = true): static
    {

        if ($condition) {
            $this->dehydrateStateUsing(
                fn($state): ?float => $state ?
                floatval(
                    Str::of($state)
                        ->replace('.', '')
                        ->replace(',', '.')
                        ->toString()
                ) :
                null
            );
        } else {
            $this->dehydrateStateUsing(null);
        }

        return $this;
    }

    public function initialValue(null|string|int|float|\Closure $value = '0,00'): static
    {
        $this->initialValue = $value;

        return $this;
    }
}
```

**Comment by leandrocfe** [comment]
@mclgms @hjJunior @AdrianoMauricio1994 
Verifiquem essa versão por favor
https://github.com/leandrocfe/filament-ptbr-form-fields/releases/tag/3.1.0

**Comment by mclgms** [comment]
Leandro
Desculpe a demora. Fiz testes e no meu projeto deu certo.
Obrigado!


Atenciosamente

Marcelo Gomes |  MG Consultoria e Serviços de TI
Fixo : (11) 2214-3585  /  Móvel: (11) 9 8364-3775




------ Mensagem Original ------
De "Leandro Ferreira" ***@***.***>
Para "leandrocfe/filament-ptbr-form-fields" 
***@***.***>
CC "Marcelo Gomes" ***@***.***>; "Mention" 
***@***.***>
Data 30/08/2024 09:13:28
Assunto Re: [leandrocfe/filament-ptbr-form-fields] [Bug]: Componente 
Money não está atualizandocorretamente os valores no Banco - Filament 
V3. (Issue #9)
